apiVersion: v1
kind: Service
metadata:
  name: echobot
  labels:
    run: echobot
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3977
    protocol: TCP
    name: http
  - port: 443
    targetPort: 3978
    protocol: TCP
    name: https
  selector:
    run: echobot